<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>regression_analysis</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Proposal.html">Proposal</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="EDA.html">EDA</a>
</li>
<li>
  <a href="regression_analysis.html">Regression</a>
</li>
<li>
  <a href="Report_V4.html">Report</a>
</li>
<li>
  <a href="https://haoyang.shinyapps.io/shiny/">shiny</a>
</li>
<li>
  <a href="https://youtu.be/展示还没定下来">
    <span class="fa fa-brands fa-youtube"></span>
     
  </a>
</li>
<li>
  <a href="mailto:ll3968@cumc.columbia.edu">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/LiutongLi053/P8105_FinalProject.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">regression_analysis</h1>

</div>


<div id="multiple-linear-regression" class="section level3">
<h3>Multiple Linear Regression</h3>
<p>First let’s fit a simpe model of only <code>Energy Insecurity</code>
and <code>Extended Power Outages</code>.</p>
<pre class="r"><code>mlr_simple = lm(mean_glth ~ EI_proportion * PO_proportion, data = regression_data)

summary(mlr_simple) |&gt;
    broom::tidy(conf.int = TRUE) |&gt;
    select(term, estimate, conf.low, conf.high, p.value) |&gt;
    knitr::kable(digits = 3, caption = &quot;MLR simple model&quot;)</code></pre>
<table>
<caption>MLR simple model</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">4.135</td>
<td align="right">-0.379</td>
<td align="right">8.649</td>
<td align="right">0.072</td>
</tr>
<tr class="even">
<td align="left">EI_proportion</td>
<td align="right">43.079</td>
<td align="right">25.095</td>
<td align="right">61.063</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">PO_proportion</td>
<td align="right">-6.480</td>
<td align="right">-27.415</td>
<td align="right">14.455</td>
<td align="right">0.536</td>
</tr>
<tr class="even">
<td align="left">EI_proportion:PO_proportion</td>
<td align="right">25.192</td>
<td align="right">-51.061</td>
<td align="right">101.445</td>
<td align="right">0.509</td>
</tr>
</tbody>
</table>
<p>More general full model.</p>
<pre class="r"><code>mlr_fit = lm(mean_glth ~ mean_mhlth + mean_depression + mean_access + mean_smoking +
    mean_binge + mean_sleep + mean_lpa + mean_diabetes + mean_bphigh + EI_proportion +
    PO_proportion, data = regression_data)

summary(mlr_fit) |&gt;
    broom::tidy(conf.int = TRUE) |&gt;
    select(term, estimate, conf.low, conf.high, p.value) |&gt;
    knitr::kable(digits = 3, caption = &quot;MLR Full Model)&quot;)</code></pre>
<table>
<caption>MLR Full Model)</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-6.425</td>
<td align="right">-10.977</td>
<td align="right">-1.873</td>
<td align="right">0.007</td>
</tr>
<tr class="even">
<td align="left">mean_mhlth</td>
<td align="right">0.558</td>
<td align="right">0.263</td>
<td align="right">0.854</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">mean_depression</td>
<td align="right">0.008</td>
<td align="right">-0.134</td>
<td align="right">0.149</td>
<td align="right">0.914</td>
</tr>
<tr class="even">
<td align="left">mean_access</td>
<td align="right">0.029</td>
<td align="right">-0.041</td>
<td align="right">0.099</td>
<td align="right">0.413</td>
</tr>
<tr class="odd">
<td align="left">mean_smoking</td>
<td align="right">-0.021</td>
<td align="right">-0.172</td>
<td align="right">0.130</td>
<td align="right">0.780</td>
</tr>
<tr class="even">
<td align="left">mean_binge</td>
<td align="right">0.004</td>
<td align="right">-0.101</td>
<td align="right">0.109</td>
<td align="right">0.939</td>
</tr>
<tr class="odd">
<td align="left">mean_sleep</td>
<td align="right">-0.101</td>
<td align="right">-0.225</td>
<td align="right">0.024</td>
<td align="right">0.110</td>
</tr>
<tr class="even">
<td align="left">mean_lpa</td>
<td align="right">0.224</td>
<td align="right">0.080</td>
<td align="right">0.369</td>
<td align="right">0.003</td>
</tr>
<tr class="odd">
<td align="left">mean_diabetes</td>
<td align="right">0.671</td>
<td align="right">0.287</td>
<td align="right">1.055</td>
<td align="right">0.001</td>
</tr>
<tr class="even">
<td align="left">mean_bphigh</td>
<td align="right">0.033</td>
<td align="right">-0.111</td>
<td align="right">0.178</td>
<td align="right">0.643</td>
</tr>
<tr class="odd">
<td align="left">EI_proportion</td>
<td align="right">12.789</td>
<td align="right">5.606</td>
<td align="right">19.971</td>
<td align="right">0.001</td>
</tr>
<tr class="even">
<td align="left">PO_proportion</td>
<td align="right">-2.130</td>
<td align="right">-4.270</td>
<td align="right">0.011</td>
<td align="right">0.051</td>
</tr>
</tbody>
</table>
<p>Check for key assumptions</p>
<pre class="r"><code>p1 = regression_data |&gt;
    modelr::add_residuals(mlr_fit) |&gt;
    modelr::add_predictions(mlr_fit) |&gt;
    ggplot(aes(x = pred, y = resid)) + geom_point(alpha = 0.5) + geom_hline(yintercept = 0,
    color = &quot;red&quot;) + labs(x = &quot;Fitted values&quot;, y = &quot;Residuals&quot;, title = &quot;Residuals vs Fitted&quot;)

p2 = ggplot(mlr_fit, aes(sample = .resid)) + stat_qq() + stat_qq_line() + labs(title = &quot;Normal Q-Q Plot of Residuals&quot;)

p1 + p2</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-6-1.png" width="90%" /></p>
<p>The linearity and constant variance assumptions are reasonably
satisfied. Overall, the normality assumption is acceptable.</p>
<p>stepwise selection</p>
<pre class="r"><code>lower_model = lm(mean_glth ~ EI_proportion + PO_proportion, data = regression_data)

step_model = step(mlr_fit, scope = list(lower = formula(lower_model), upper = formula(mlr_fit)),
    direction = &quot;both&quot;, trace = FALSE)

summary(step_model) |&gt;
    broom::tidy(conf.int = TRUE) |&gt;
    select(term, estimate, conf.low, conf.high, p.value) |&gt;
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-5.635</td>
<td align="right">-8.222</td>
<td align="right">-3.049</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">mean_mhlth</td>
<td align="right">0.556</td>
<td align="right">0.386</td>
<td align="right">0.725</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">mean_sleep</td>
<td align="right">-0.115</td>
<td align="right">-0.215</td>
<td align="right">-0.015</td>
<td align="right">0.025</td>
</tr>
<tr class="even">
<td align="left">mean_lpa</td>
<td align="right">0.226</td>
<td align="right">0.122</td>
<td align="right">0.330</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">mean_diabetes</td>
<td align="right">0.744</td>
<td align="right">0.460</td>
<td align="right">1.027</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">EI_proportion</td>
<td align="right">13.841</td>
<td align="right">7.566</td>
<td align="right">20.116</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">PO_proportion</td>
<td align="right">-2.102</td>
<td align="right">-3.984</td>
<td align="right">-0.221</td>
<td align="right">0.029</td>
</tr>
</tbody>
</table>
<p>The final model based on MLR results in: Prevalence of fair/poor
general health = -5.635 + 0.556 Prevalence of poor mental health - 0.115
Prevalence of insufficient sleep+ 0.226 Prevalence of no leisure-time
physical activity + 0.744 Prevalence of diabetes + 13.841 Energy
Insecurity proportion - 2.102 Power Outage proportion.</p>
</div>
<div id="elastic-net" class="section level3">
<h3>ELASTIC NET</h3>
<p>Because our EDA shows that the two electricity variables are strongly
correlated, the MLR model is likely to produce unstable estimates. Using
Elastic Net helps prevent overfitting while simultaneously stabilizing
the coefficient estimates and shrinking unnecessary parameters toward
zero. Hence, we expec that this may leads to a more robust and
interpretable model.</p>
<p>We set <span class="math inline">\(\alpha = 0.5\)</span> to balance
the Ridge and Lasso penalties within the Elastic Net framework. We then
used <code>cv.glmnet()</code> to identify the optimal value of <span
class="math inline">\(\lambda\)</span>. This function performs 10-fold
cross-validation by default, repeatedly splitting the data into ten
parts, training the model on nine parts, and validating it on the
remaining part to select the <span
class="math inline">\(\lambda\)</span> that minimizes the
cross-validated error.</p>
<pre class="r"><code>y &lt;- regression_data$mean_glth

x &lt;- regression_data |&gt;
    select(mean_mhlth, mean_depression, mean_access, mean_smoking, mean_binge, mean_sleep,
        mean_lpa, mean_diabetes, mean_bphigh, EI_proportion, PO_proportion) |&gt;
    as.matrix()

cv_en &lt;- cv.glmnet(x, y, alpha = 0.5)
lambda_best &lt;- cv_en$lambda.min
fit_en &lt;- glmnet(x, y, alpha = 0.5, lambda = lambda_best)

coef_en &lt;- coef(fit_en)
coef_en</code></pre>
<pre><code>## 12 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                           s0
## (Intercept)     -7.217287806
## mean_mhlth       0.487334980
## mean_depression  0.004961792
## mean_access      0.045936144
## mean_smoking     0.027022483
## mean_binge       .          
## mean_sleep       .          
## mean_lpa         0.193657398
## mean_diabetes    0.534606842
## mean_bphigh      0.032181274
## EI_proportion   10.817492000
## PO_proportion   -0.819165535</code></pre>
<pre class="r"><code>pred_en &lt;- predict(fit_en, x) |&gt;
    as.numeric()

r2_en &lt;- 1 - sum((y - pred_en)^2)/sum((y - mean(y))^2)
r2_en</code></pre>
<pre><code>## [1] 0.9567934</code></pre>
<pre class="r"><code>rmse_en &lt;- sqrt(mean((y - pred_en)^2))
rmse_en</code></pre>
<pre><code>## [1] 0.6592415</code></pre>
</div>
<div id="cross-validation" class="section level3">
<h3>Cross Validation</h3>
<pre class="r"><code>cv_df =
  crossv_mc(regression_data, n = 100) |&gt;
  mutate(
    train = map(train, as_tibble),
    test  = map(test, as_tibble)
  )

cv_df =
  cv_df |&gt;
  mutate(
    # Model 1: Full MLR
    model_1 = map(train, \(df)
      lm(mean_glth ~ mean_mhlth + mean_depression + mean_access +
           mean_smoking + mean_binge + mean_sleep + mean_lpa +
           mean_diabetes + mean_bphigh + EI_proportion + PO_proportion,
         data = df)
    ),

    # Model 2: Elastic Net (refit λ for each split)
    model_2 = map(train, \(df) {
      y &lt;- df$mean_glth
      X &lt;- df |&gt;
        dplyr::select(
          mean_mhlth, mean_depression, mean_access, mean_smoking,
          mean_binge, mean_sleep, mean_lpa, mean_diabetes, mean_bphigh,
          EI_proportion, PO_proportion
        ) |&gt;
        as.matrix()

      cvfit &lt;- cv.glmnet(X, y, alpha = 0.5)
      best_lambda &lt;- cvfit$lambda.min
      glmnet(X, y, alpha = 0.5, lambda = best_lambda)
    }),

    # Model 3: Electricity-only + Interaction
    model_3 = map(train, \(df)
      lm(mean_glth ~ EI_proportion * PO_proportion, data = df)
    )
  )

cv_df =
  cv_df |&gt;
  mutate(
    rmse_model_1 = map2_dbl(model_1, test, \(fit, df)
      rmse(fit, df)
    ),

    rmse_model_2 = map2_dbl(model_2, test, \(fit, df) {
      y_test &lt;- df$mean_glth
      X_test &lt;- df |&gt;
        dplyr::select(
          mean_mhlth, mean_depression, mean_access, mean_smoking,
          mean_binge, mean_sleep, mean_lpa, mean_diabetes, mean_bphigh,
          EI_proportion, PO_proportion
        ) |&gt; as.matrix()
      pred &lt;- predict(fit, X_test) |&gt; as.numeric()
      sqrt(mean((y_test - pred)^2))
    }),

    rmse_model_3 = map2_dbl(model_3, test, \(fit, df)
      rmse(fit, df)
    )
  )</code></pre>
<pre class="r"><code>cv_df |&gt;
    dplyr::select(starts_with(&quot;rmse&quot;)) |&gt;
    pivot_longer(everything(), names_to = &quot;model&quot;, values_to = &quot;rmse&quot;, names_prefix = &quot;rmse_&quot;) |&gt;
    ggplot(aes(x = model, y = rmse, fill = model)) + geom_violin() + ggtitle(&quot;Comparison of RMSE Across Models&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-10-1.png" width="90%" /></p>
<p>Model based on Elastic Net achieves the lowest and most stable RMSE
across the cross-validation replicates, indicating superior predictive
performance and generalization ability. The full MLR model performs
moderately well but shows higher variability, suggesting mild
overfitting. The electricity-only model has the highest RMSE, confirming
that electricity variables alone are insufficient to explain variations
in mean_glth.</p>
</div>
<div id="bootstrap" class="section level3">
<h3>Bootstrap</h3>
<p>After fitting the MLR model, we applied the bootstrap to evaluate how
stable our results are under repeated sampling. The usual regression
output relies on assumptions such as normality and constant variance,
which may not fully hold in our data. Bootstrap resampling lets us
approximate the sampling distribution of key estimates directly from the
data, providing more robust standard errors and confidence intervals.
This helps us assess whether the model’s conclusions remain consistent
across resampled datasets.</p>
<pre class="r"><code>boot_straps = regression_data |&gt;
    modelr::bootstrap(n = 5000)

boot_results = boot_straps |&gt;
    mutate(models = map(strap, \(s) {
        df = s$data

        Xb = df |&gt;
            select(mean_mhlth, mean_depression, mean_access, mean_smoking, mean_binge,
                mean_sleep, mean_lpa, mean_diabetes, mean_bphigh, EI_proportion,
                PO_proportion) |&gt;
            as.matrix()

        yb = df$mean_glth

        cvb = cv.glmnet(Xb, yb, alpha = 0.5)
        cb = coef(cvb, s = cvb$lambda.min)

        tibble(term = rownames(cb), estimate = as.numeric(cb))
    })) |&gt;
    select(-strap) |&gt;
    unnest(models) |&gt;
    filter(term != &quot;(Intercept)&quot;)

boot_se = boot_results |&gt;
    group_by(term) |&gt;
    summarize(boot_se = sd(estimate))

boot_se</code></pre>
<pre><code>## # A tibble: 11 × 2
##    term             boot_se
##    &lt;chr&gt;              &lt;dbl&gt;
##  1 EI_proportion   0.466   
##  2 PO_proportion   0.328   
##  3 mean_access     0.00374 
##  4 mean_binge      0       
##  5 mean_bphigh     0.000639
##  6 mean_depression 0.00201 
##  7 mean_diabetes   0.0306  
##  8 mean_lpa        0.00685 
##  9 mean_mhlth      0.0162  
## 10 mean_sleep      0.0227  
## 11 mean_smoking    0.00901</code></pre>
<p>The bootstrap results indicate notable differences in coefficient
stability across predictors in the Elastic Net model. Most variables,
such as mean_access, mean_binge, mean_bphigh, mean_mhlth, mean_sleep,
and mean_smoking, exhibit very small bootstrap standard errors,
suggesting that their estimated effects remain highly consistent across
resampled datasets. In contrast, EI_proportion and PO_proportion show
substantially larger standard errors, indicating considerable
variability in their estimated coefficients and reduced stability under
repeated sampling. Overall, the bootstrap results suggest that the
majority of predictors contribute reliably to the model, while the two
proportion-based variables demonstrate much weaker stability.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
